dist: trusty

language: python

python: 3.6


# language: c
# sudo: false



notifications:
  email:
    recipients:
      - steveri@stanford.edu
    # on_success: never # default: change
    on_failure: always # default: always

install:
    - pip install virtualenv

script:
  # Current working directory: /home/travis/build/steveri/easysteps
  - set -e ; # Die at first error
  - test/test.sh
  - easysteps-alt/test/test.sh



#   # set -e => exit on failure "you can sandwich stuff in script w/ set -e and set +e."
#   - set -e
# 
#   ### FFT REGRESSIONS
#   - cd ${TRAVIS_BUILD_DIR}
#   - mkdir regression; cd regression
#   # - ls -l ../bin
#   - ../bin/golden_test.csh -sim verilator |& tee test_results.log | egrep 'PASS|FAIL|ERR'
#   #
#   # Here's a tricky thing...it passes when it fails and it fails when it passes :(
#   # Also---FIXME---above command should be responsible for PASS/FAIL exit codes
#   - egrep 'FAIL|ERR' test_results.log && exit 13 || echo okay
# 
#   ### SIMV ANALYZER
#   # I have this test for the analyzer, why not use it.
#   - cd ${TRAVIS_BUILD_DIR}/bin/simv_analysis; make test
